### ISSUE TITLE
getting error Exception: Prerequisite not met : No OIDC provider found for cluster 'my-cluster'!

### ISSUE THREAD

**Issue by bkrajendra** [aws-samples/amazon-efs-developer-zone#7]
I am trying to set up an a efs using Python script with dynamic provisioning.
getting an error: Exception: Prerequisite not met : No OIDC provider found for cluster 'my-cluster'!

Env: python3
OS: MacOs

**Comment by debnsuma** [comment]
Whats the output of this ? Did you follow this : https://github.com/aws-samples/amazon-efs-developer-zone/tree/main/application-integration/container/eks/dynamic_provisioning ? 
 
 $ export CLUSTER_NAME=efsworkshop-eksctl
 $ eksctl utils associate-iam-oidc-provider --cluster $CLUSTER_NAME --approve 
 
 I am not able to reproduce the issue
